sudo: required

language: python

services:
  - docker

before_install:
  - docker build -t eebook/catalog .

env:
  global:
  - ENCRYPTION_LABEL: d874329ef0dd
  - COMMIT_AUTHOR_EMAIL: "hejun1874@gmail.com"

script:
  - docker run -v $(pwd):/src eebook/catalog make test
  - bash ./deploy_travis.sh


